/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { VacationRuleService } from "../vacationRule.service";
import { VacationRuleCreateInput } from "./VacationRuleCreateInput";
import { VacationRule } from "./VacationRule";
import { VacationRuleFindManyArgs } from "./VacationRuleFindManyArgs";
import { VacationRuleWhereUniqueInput } from "./VacationRuleWhereUniqueInput";
import { VacationRuleUpdateInput } from "./VacationRuleUpdateInput";

export class VacationRuleControllerBase {
  constructor(protected readonly service: VacationRuleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VacationRule })
  async createVacationRule(
    @common.Body() data: VacationRuleCreateInput
  ): Promise<VacationRule> {
    return await this.service.createVacationRule({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        policy: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [VacationRule] })
  @ApiNestedQuery(VacationRuleFindManyArgs)
  async vacationRules(@common.Req() request: Request): Promise<VacationRule[]> {
    const args = plainToClass(VacationRuleFindManyArgs, request.query);
    return this.service.vacationRules({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        policy: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VacationRule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async vacationRule(
    @common.Param() params: VacationRuleWhereUniqueInput
  ): Promise<VacationRule | null> {
    const result = await this.service.vacationRule({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        policy: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VacationRule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateVacationRule(
    @common.Param() params: VacationRuleWhereUniqueInput,
    @common.Body() data: VacationRuleUpdateInput
  ): Promise<VacationRule | null> {
    try {
      return await this.service.updateVacationRule({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          policy: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VacationRule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteVacationRule(
    @common.Param() params: VacationRuleWhereUniqueInput
  ): Promise<VacationRule | null> {
    try {
      return await this.service.deleteVacationRule({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          policy: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
