/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { VacationPolicyService } from "../vacationPolicy.service";
import { VacationPolicyCreateInput } from "./VacationPolicyCreateInput";
import { VacationPolicy } from "./VacationPolicy";
import { VacationPolicyFindManyArgs } from "./VacationPolicyFindManyArgs";
import { VacationPolicyWhereUniqueInput } from "./VacationPolicyWhereUniqueInput";
import { VacationPolicyUpdateInput } from "./VacationPolicyUpdateInput";

export class VacationPolicyControllerBase {
  constructor(protected readonly service: VacationPolicyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VacationPolicy })
  async createVacationPolicy(
    @common.Body() data: VacationPolicyCreateInput
  ): Promise<VacationPolicy> {
    return await this.service.createVacationPolicy({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [VacationPolicy] })
  @ApiNestedQuery(VacationPolicyFindManyArgs)
  async vacationPolicies(
    @common.Req() request: Request
  ): Promise<VacationPolicy[]> {
    const args = plainToClass(VacationPolicyFindManyArgs, request.query);
    return this.service.vacationPolicies({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VacationPolicy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async vacationPolicy(
    @common.Param() params: VacationPolicyWhereUniqueInput
  ): Promise<VacationPolicy | null> {
    const result = await this.service.vacationPolicy({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VacationPolicy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateVacationPolicy(
    @common.Param() params: VacationPolicyWhereUniqueInput,
    @common.Body() data: VacationPolicyUpdateInput
  ): Promise<VacationPolicy | null> {
    try {
      return await this.service.updateVacationPolicy({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VacationPolicy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteVacationPolicy(
    @common.Param() params: VacationPolicyWhereUniqueInput
  ): Promise<VacationPolicy | null> {
    try {
      return await this.service.deleteVacationPolicy({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
