/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { VacationPolicy } from "./VacationPolicy";
import { VacationPolicyCountArgs } from "./VacationPolicyCountArgs";
import { VacationPolicyFindManyArgs } from "./VacationPolicyFindManyArgs";
import { VacationPolicyFindUniqueArgs } from "./VacationPolicyFindUniqueArgs";
import { CreateVacationPolicyArgs } from "./CreateVacationPolicyArgs";
import { UpdateVacationPolicyArgs } from "./UpdateVacationPolicyArgs";
import { DeleteVacationPolicyArgs } from "./DeleteVacationPolicyArgs";
import { User } from "../../user/base/User";
import { VacationPolicyService } from "../vacationPolicy.service";
@graphql.Resolver(() => VacationPolicy)
export class VacationPolicyResolverBase {
  constructor(protected readonly service: VacationPolicyService) {}

  async _vacationPoliciesMeta(
    @graphql.Args() args: VacationPolicyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [VacationPolicy])
  async vacationPolicies(
    @graphql.Args() args: VacationPolicyFindManyArgs
  ): Promise<VacationPolicy[]> {
    return this.service.vacationPolicies(args);
  }

  @graphql.Query(() => VacationPolicy, { nullable: true })
  async vacationPolicy(
    @graphql.Args() args: VacationPolicyFindUniqueArgs
  ): Promise<VacationPolicy | null> {
    const result = await this.service.vacationPolicy(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => VacationPolicy)
  async createVacationPolicy(
    @graphql.Args() args: CreateVacationPolicyArgs
  ): Promise<VacationPolicy> {
    return await this.service.createVacationPolicy({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => VacationPolicy)
  async updateVacationPolicy(
    @graphql.Args() args: UpdateVacationPolicyArgs
  ): Promise<VacationPolicy | null> {
    try {
      return await this.service.updateVacationPolicy({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => VacationPolicy)
  async deleteVacationPolicy(
    @graphql.Args() args: DeleteVacationPolicyArgs
  ): Promise<VacationPolicy | null> {
    try {
      return await this.service.deleteVacationPolicy(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(
    @graphql.Parent() parent: VacationPolicy
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
